assets:
  - connection_id: ee23720c-c82f-45be-ab40-f72dcf8ac3cd
    group_name: zendesk
    dataset_id: kipptaf_zendesk
    destination_tables:
      - groups
      - organizations
      - ticket_audits
      - ticket_fields
      - ticket_metrics
      - tickets
      - user_identities
      - users
  - connection_id: e4856fb7-1f97-4bcd-bc4e-e616c5ae4e52
    group_name: kippadb
    kinds:
      - salesforce
    dataset_id: kipptaf_kippadb
    destination_tables:
      - Account
      - Application__c
      - College_Persistence__c
      - Contact
      - Contact_Note__c
      - Employment__c
      - Enrollment__c
      - GPA__c
      - Internships_Programs__c
      - RecordType
      - Standardized_Test__c
      - Subsequent_Financial_Aid_Award__c
      - Term__c
      - User
      # - Application__History
      # - Application_History__c
      # - Application_Status_History__c
      # - Attachment
      # - ContentDocument
      # - Counseling_Case__c
      # - Enrollment__History
      # - Event
      # - KIPP_Aid__c
      # - Marking_Period__c
      # - Relationship__c
      # - Task
      # - Term__History
