assets:
  # not using partitions
  - asset_name: cc
    partition_column: transaction_date
  - asset_name: assignmentcategoryassoc
    partition_column: whenmodified
  # - asset_name: assignmentsection
  #   partition_column: whenmodified
  # - asset_name: codeset
  #   partition_column: whenmodified
  # - asset_name: districtteachercategory
  #   partition_column: whenmodified
  # - asset_name: emailaddress
  #   partition_column: whenmodified
  # - asset_name: gradecalcformulaweight
  #   partition_column: whenmodified
  # - asset_name: gradecalcschoolassoc
  #   partition_column: whenmodified
  # - asset_name: gradecalculationtype
  #   partition_column: whenmodified
  # - asset_name: gradeformulaset
  #   partition_column: whenmodified
  # - asset_name: gradescaleitem
  #   partition_column: whenmodified
  # - asset_name: gradeschoolconfig
  #   partition_column: whenmodified
  # - asset_name: gradeschoolformulaassoc
  #   partition_column: whenmodified
  # - asset_name: gradesectionconfig
  #   partition_column: whenmodified
  # - asset_name: originalcontactmap
  #   partition_column: whenmodified
  # - asset_name: person
  #   partition_column: whenmodified
  # - asset_name: personaddress
  #   partition_column: whenmodified
  # - asset_name: personaddressassoc
  #   partition_column: whenmodified
  # - asset_name: personemailaddressassoc
  #   partition_column: whenmodified
  # - asset_name: personphonenumberassoc
  #   partition_column: whenmodified
  # - asset_name: phonenumber
  #   partition_column: whenmodified
  # - asset_name: roledef
  #   partition_column: whenmodified
  # - asset_name: s_nj_crs_x
  #   partition_column: whenmodified
  # - asset_name: s_nj_ren_x
  #   partition_column: whenmodified
  # - asset_name: s_nj_stu_x
  #   partition_column: whenmodified
  #   op_tags:
  #     dagster-k8s/config:
  #       container_config:
  #         resources:
  #           requests:
  #             memory: 1.0Gi
  # - asset_name: s_nj_usr_x
  #   partition_column: whenmodified
  # - asset_name: schoolstaff
  #   partition_column: whenmodified
  # - asset_name: sectionteacher
  #   partition_column: whenmodified
  # - asset_name: studentcontactassoc
  #   partition_column: whenmodified
  # - asset_name: studentcontactdetail
  #   partition_column: whenmodified
  # - asset_name: studentcorefields
  #   partition_column: whenmodified
  # - asset_name: studentrace
  #   partition_column: whenmodified
  # - asset_name: teachercategory
  #   partition_column: whenmodified
  # - asset_name: u_clg_et_stu
  #   partition_column: whenmodified
  # - asset_name: u_clg_et_stu_alt
  #   partition_column: whenmodified
  # - asset_name: u_def_ext_students
  #   partition_column: whenmodified
  # - asset_name: u_studentsuserfields
  #   partition_column: whenmodified
  # - asset_name: users
  #   partition_column: whenmodified
