endpoints:
  - endpoint: terms
    api_version: v1
  - endpoint: roster-assignments
    api_version: beta
  - endpoint: users
    api_version: v1
    params:
      IncludeInactive: Y
  - endpoint: rosters
    api_version: v1
    params:
      show_inactive: Y
  - endpoint: students
    api_version: v1
    params:
      IncludeCustomFields: Y
      IncludeUnenrolled: Y
      IncludeParents: Y
  # - endpoint: lists
  #   api_version: v1
  # - endpoint: dff/stats
  #   api_version: v1
