version: 2
models:
  - name: stg_powerschool__gradeschoolconfig
    columns:
      - name: gradecalcpreferenceorder
        data_type: string
      - name: defaultroundingrule
        data_type: string
      - name: calculationmetric
        data_type: string
      - name: higherlevelstndmetric
        data_type: string
      - name: recentscoreweightlist
        data_type: string
      - name: calcmetricschoolfromstd
        data_type: string
      - name: sectionnames
        data_type: string
      - name: standardtraditionalorder
        data_type: string
      - name: whocreated
        data_type: string
      - name: whencreated
        data_type: timestamp
      - name: whomodified
        data_type: string
      - name: whenmodified
        data_type: timestamp
      - name: gradeschoolconfigid
        data_type: int64
      - name: schoolsdcid
        data_type: int64
      - name: yearid
        data_type: int64
      - name: defaultdecimalcount
        data_type: int64
      - name: iscalcformulaeditable
        data_type: int64
      - name: isdropscoreeditable
        data_type: int64
      - name: iscalcprecisioneditable
        data_type: int64
      - name: iscalcmetriceditable
        data_type: int64
      - name: isrecentscoreeditable
        data_type: int64
      - name: ishigherstndautocalc
        data_type: int64
      - name: ishigherstndcalceditable
        data_type: int64
      - name: ishighstandardeditable
        data_type: int64
      - name: iscalcmetricschooledit
        data_type: int64
      - name: isstandardsshown
        data_type: int64
      - name: isstandardsshownonasgmt
        data_type: int64
      - name: istraditionalgradeshown
        data_type: int64
      - name: iscitizenshipdisplayed
        data_type: int64
      - name: termbinlockoffset
        data_type: int64
      - name: lockwarningoffset
        data_type: int64
      - name: issectstndweighteditable
        data_type: int64
      - name: minimumassignmentvalue
        data_type: int64
      - name: isgradescaleteachereditable
        data_type: int64
      - name: isstandardslimited
        data_type: int64
      - name: isstandardslimitededitable
        data_type: int64
      - name: isusingpercentforstndautocalc
        data_type: int64
