resources:
  db:
    config:
      dialect: mssql
      driver: pyodbc
      mssql_driver: ODBC Driver 18 for SQL Server
      username:
        env: MSSQL_USERNAME
      password:
        env: MSSQL_PASSWORD
      host:
        env: MSSQL_HOST
      port:
        env: MSSQL_PORT
      database:
        env: MSSQL_DATABASE
  file_manager:
    config:
      gcs_prefix: datagun
